#!/usr/bin/env python
 
import os
import sys
 
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 
			     'linux4chemistry'))
 
os.environ['DJANGO_SETTINGS_MODULE'] = 'linux4chemistry.settings'
 
zvirtenv = os.path.join(os.environ['OPENSHIFT_PYTHON_DIR'],
			'virtenv', 'bin', 'activate_this.py')
try:
    execfile(zvirtenv, dict(__file__ = zvirtenv) )
except IOError:
    pass

#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
#
 
import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
